### ISSUE TITLE
Pubrules crashes if the SOTD section is empty

### ISSUE THREAD

**Issue by plehegar** [w3c/specberus#772]
This happens at least on the CR profile.

The crash happens at
 https://github.com/w3c/specberus/blob/master/lib/validator.js#L332

[[
specberus\lib\validator.js:332
      for (var i = 0; i < candidates.length; i++) {
                                     ^

TypeError: Cannot read property 'length' of null
    at Specberus.getFeedbackDueDate (specberus\lib\validator.js:332:38)
    at Object.exports.check (specberus\lib\rules\sotd\cr-end.js:13:26)
    at specberus\lib\validator.js:116:18
    at Array.forEach (<anonymous>)
    at doValidation (specberus\lib\validator.js:112:23)
    at Specberus.loadSource (specberus\lib\validator.js:426:5)
    at specberus\lib\validator.js:412:18
    at Request.callback (specberus\node_modules\superagent\lib\node\index.js:716:12)
    at Stream.parser (specberus\node_modules\superagent\lib\node\index.js:916:18)
    at emitNone (events.js:111:20)
]]

cc @svgeesus

**Comment by deniak** [comment]
The PR looks good but I want to make sure I understand the problem correctly. The title of this issue mentions an empty SOTD but iiuc, the problem occurs when there's no matching dates in the SOTD. If so, then the issue is indeed closed.

**Comment by plehegar** [comment]
yes, it does fix the issue. Specberus didn't crash after fixing that and reported a lot of issues since there was no SOTD.
