### ISSUE TITLE
Only check TR documents and submissions

### ISSUE THREAD

**Issue by jennyliang220** [w3c/specberus#978]

**Comment by deniak** [comment]
When using the `auto detect` profile, pubrules should report an error if the document isn't recognized as a /TR document or a member submission

**Comment by jennyliang220** [comment]
Should report an error:
- https://drafts.csswg.org/css2/ is an `Editor’s Draft`, is not TR document, should report an error.
- https://www.w3.org/2020/Process-20200915/ is process document, not a TR document, should report an error.

Should pass:
- https://www.w3.org/Submission/2020/SUBM-prism-20200910/ is a `Member Submission`, is `submission`, should pass.
- https://www.w3.org/TR/2020/CRD-webrtc-20201008/ is `CR`, one of TR, should pass.

**Comment by deniak** [comment]
@jennyliang220 there's a regression here.
@iherman  tried to check a respec source document (https://raw.githack.com/w3c/did-core/main/index.html) and pubrules crashed with the following exception:

```
TypeError: Cannot read property 'length' of null
    at Specberus.getDelivererIDs (specberus/lib/validator.js:452:39)
    at Object.exports.check (specberus/lib/rules/sotd/group-homepage.js:12:25)
    at specberus/lib/validator.js:154:18
    at Array.forEach (<anonymous>)
    at doValidation (specberus/lib/validator.js:150:23)
    at Specberus.loadSource (specberus/lib/validator.js:516:5)
    at specberus/lib/validator.js:502:18
    at Request.callback (specberus/node_modules/superagent/lib/node/index.js:894:12)
    at IncomingMessage.<anonymous> (specberus/node_modules/superagent/lib/node/index.js:1127:20)
    at Stream.emit (events.js:327:22)

```
